-- This script was generated by a beta version of the Schema Diff utility in pgAdmin 4. 
-- This version does not include dependency resolution, and may require manual changes 
-- to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
CREATE TABLE public."Severities"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Enabled" boolean NOT NULL DEFAULT true,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "DisplayColor" text COLLATE pg_catalog."default" NOT NULL DEFAULT '#000000'::text,
    "Priority" integer NOT NULL DEFAULT 10,
    CONSTRAINT "Severities_pkey" PRIMARY KEY ("ID")
)

TABLESPACE pg_default;

ALTER TABLE public."Severities"
    OWNER to tixter;

END;