-- This script was generated by a beta version of the Schema Diff utility in pgAdmin 4. 
-- This version does not include dependency resolution, and may require manual changes 
-- to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
CREATE TABLE public."Groups"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Permissions" json NOT NULL,
    CONSTRAINT "Groups_pkey" PRIMARY KEY ("ID")
)

TABLESPACE pg_default;

ALTER TABLE public."Groups"
    OWNER to tixter;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."Users"
 --     ALTER COLUMN "ID" TYPE bigint;

ALTER TABLE public."Users"
    ADD COLUMN "Permissions" json NULL;

END;