-- This script was generated by a beta version of the Schema Diff utility in pgAdmin 4. 
-- This version does not include dependency resolution, and may require manual changes 
-- to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
CREATE TABLE public."Projects"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Projects_pkey" PRIMARY KEY ("ID")
)

TABLESPACE pg_default;

ALTER TABLE public."Projects"
    OWNER to tixter;

CREATE TABLE public."Queue"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Project" bigint NOT NULL,
    CONSTRAINT "Queue_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Queue_Projekt" FOREIGN KEY ("Project")
        REFERENCES public."Projects" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Queue"
    OWNER to tixter;

CREATE TABLE public."map_User_Group"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "UserID" bigint NOT NULL,
    "GroupID" bigint NOT NULL,
    CONSTRAINT "map_User_Group_pkey" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_GroupID_Group" FOREIGN KEY ("GroupID")
        REFERENCES public."Groups" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_UserID_User" FOREIGN KEY ("UserID")
        REFERENCES public."Users" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public."map_User_Group"
    OWNER to tixter;

END;