-- This script was generated by a beta version of the Schema Diff utility in pgAdmin 4. 
-- This version does not include dependency resolution, and may require manual changes 
-- to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the ID column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."Users"
 --     ALTER COLUMN "ID" TYPE bigint;

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Username column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."Users"
 --     ALTER COLUMN "Username" TYPE text COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Password column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."Users"
 --     ALTER COLUMN "Password" TYPE text COLLATE pg_catalog."default";

-- WARNING:
-- The SQL statement below would normally be used to alter the datatype for the Mail column, however,
-- the current datatype cannot be cast to the target datatype so this conversion cannot be made automatically.

 -- ALTER TABLE public."Users"
 --     ALTER COLUMN "Mail" TYPE text COLLATE pg_catalog."default";

ALTER TABLE public."Users"
    ADD COLUMN "Firstname" text COLLATE pg_catalog."default";

ALTER TABLE public."Users"
    ADD COLUMN "Lastname" text COLLATE pg_catalog."default";

END;